### ISSUE TITLE
Running issue

### ISSUE THREAD

**Issue by gmzang** [adler-j/learned_primal_dual#5]
Hi, 
I had one issue when running the code in ellipses :

  File "C:\Users\ZG\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 848, in _get_single_variable
    name, "".join(traceback.format_list(tb))))

ValueError: Variable primal_iterate_0/conv2d/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

Do you know what's the issue? 
Thanks.

**Comment by adler-j** [comment]
You need to restart the graph between each run. If you don't then it will try creating new variables for each time you run the code (and fail).

See e.g. https://stackoverflow.com/questions/45951037/tensorflow-variable-w3-already-exists-disallowed/45951579 for more information.

**Comment by gmzang** [comment]
Adler,
Thanks a lot for your prompt reply. Yes, when restart the spyder, it seems working fine now.
And i am running the learned_chambolle_pock demo, hopefully some interesting results will be shown soon.

Another issue is that it is running with CPU, which is kind of slow. It prints at the beginning that:
Found no GPUs, doing nothing. Any hint for this? I have GPUs on the machine.
Thanks again .

**Comment by adler-j** [comment]
Do you have a GPU installation of tensorflow? There are separate installations for CPU and GPU

**Comment by gmzang** [comment]
That's true, Adler, thanks for your kind help.  After install gpu version of tensorflow, it show one error as below when running learned_chambolle_pock demo :

  File "C:\Users\ZANGG\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)

ImportError: Traceback (most recent call last):
  File "C:\Users\ZANGG\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\ZANGG\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\ZANGG\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\ZANGG\AppData\Local\Continuum\anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\ZANGG\AppData\Local\Continuum\anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


Do you know what i can do for this? 
Thanks.

**Comment by adler-j** [comment]
Have you read https://www.tensorflow.org/install/errors? This is typically due to missing cuDNN.
